<template>
    <div class="modal-overlay">
        <div class="modal">
            <canvas id="myChart"></canvas>
        </div>
        <div class="close">
          <v-btn icon="mdi-close-circle"
            class="btn-close"
            @click="close"
            >      
          </v-btn>
        </div>
    </div>
</template>

<script>
  import Chart from 'chart.js/auto';
  import { useTheme } from 'vuetify'

  export default {
    name: 'GraphViewer',
    props: {
      /**
       * Sets file path of output.txt generated by the backend after sheet music and audio comparison
       */
      outputFilePath: String
    },
    data() {
      return {
        userData: [],
        sheetData: [],
        notes: []
      }
    },
    methods: {
      /**
       * On click function to close the modal containing graph
       * @public This is a public method
       */
      close() {
        /**
         * Close event.
         */
        this.$emit('close');
      },
    },
    created() {
      /**
       * Sets file path of output.txt generated by the backend after sheet music and audio comparison
       * @public This is a public method
       */
      console.log('created hook called');
      console.log(this.outputFilePath);
      import(`raw-loader!../../src-tauri/resources/outputs/${this.outputFilePath}`).then(module => {
        return module.default;
      }).then(fileContent => {
        let userData = [];
        let sheetData = [];
        let notes = [];

        let user = false;
        let sheet = false;
        fileContent.split('\n').forEach(element => {
          let val0 = element.split(' ')[0];
          let val1 = element.split(' ')[1];
          let val2 = element.split(' ')[2];
          if (val0 === "User") {
            user = true;
            sheet = false;
          }
          else if (val0 === "Sheet") {
            user = false;
            sheet = true;
          }
          
          if (user && !isNaN(val0) && !isNaN(val1)) {
            userData.push({x: [val0, val1], y: val2});
            if (notes.indexOf(val2) === -1) {
              notes.push(val2);
            }
          }
          if (sheet && !isNaN(val0) && !isNaN(val1)) {
            sheetData.push({x: [val0, val1], y: val2});
            if (notes.indexOf(val2) === -1) {
              notes.push(val2);
            }
          }
        });

        this.userData = userData;
        this.sheetData = sheetData;
        this.notes = notes;
      }).catch(error => {
        console.error(`Error loading file: ${this.outputFilePath}`, error);
      });
    },
    mounted() {
      const theme = useTheme()
      this.$el.style.setProperty('--success', theme.global.current.value.colors.success);
    },
    computed: {
      chartData() {
        return {
          labels: this.notes,
          datasets: [
            {
              label: 'Sheet Notes',
              data: this.sheetData,
              borderWidth: 1,
              barPercentage: 0.5,
            },
            {
              label: 'User Notes',
              data: this.userData,
              borderWidth: 1,
              barPercentage: 0.5,
            },
          ]
        }
      }
    },
    watch: {
      chartData: function () {
        const ctx = document.getElementById('myChart');
        const myChart = new Chart(ctx, {
          type: 'bar',
          data: this.chartData,
          options: {
            indexAxis: 'y',
            scales: {
              x: {
                min: 0,
                title: {
                  display: true,
                  text: 'Time (s)',
                  font: {
                    size: 15,
                  } 
                },
                ticks: {
                  font: {
                    weight: 'bold',
                    size: 15
                  }
                },
                grid: {
                  color: '#b8b0b0',
                  lineWidth: 0.2
                }
              },
              y: {
                  title: {
                    display: true,
                    text: 'Notes',
                    font: {
                      size: 15,
                    } 
                  },
                  ticks: {
                    font: {
                      weight: 'bold',
                      size: 15
                    }
                  },
                  grid: {
                    color: '#b8b0b0',
                    lineWidth: 0.2
                  }
              },
            },
            plugins: {
              legend: {
                  labels: {
                      font: {
                          style: 'bold',
                          weight: '600',
                      }
                  }
              }
            }
          }
      });
      myChart;
      }
    }
  };
</script>

<style>
.modal-overlay {
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  display: flex;
  justify-content: center;
  background-color: #000000da;
}
.modal {
  background-color: var(--success);
  height: 75%;
  width: 75%;
  padding: 60px 0;
  margin-top: 10%;
  margin-left: 20%;
}
.close {
  margin: 10% 0 0 10px;
  cursor: pointer;
}
.temp {
    color: blue;
}
.btn-close {
  width: 40px;
  height: 40px;
  border-radius: 50%;
}
#myChart {
  display: block;
  margin: 0 auto;
  width: 100%;
}
</style>

<docs>
  GraphViewer is the component that takes care of rendering the graph of notes vs time of both sheet music and
  audio. It receives the txt file as a prop from ResultsTable.vue, parses it using 'raw-loader', uses Chart.js
  to build a graph, and displays it on a vue modal.
</docs>